// src/lib/components/CFDT.svelte
<script lang="ts">
  import { dataset } from "$lib/data.svelte";

  let rows = $derived.by(() => {
    const rows = [];
    let cf = 0;
    for (const x of dataset.unique) {
      const f = dataset.frequencies.get(x)!;
      cf += f;
      rows.push([x, f, f * x, cf, (cf / dataset.size) * 100]);
    }
    return rows;
  });
</script>

<table>
  <thead>
    <tr>
      <th title="Score">x</th>
      <th title="Frequency">f</th>
      <th>fx</th>
      <th title="Cumulative Frequency">cf</th>
      <th title="Cumulative Percentage (%)">cp (%)</th>
    </tr>
  </thead>
  <tbody>
    {#each rows as [x, f, fx, cf, cp]}
      <tr>
        <td>{x}</td>
        <td>{f}</td>
        <td>{fx}</td>
        <td>{cf}</td>
        <td title={cp.toString()}>{cp.toFixed(2)}</td>
      </tr>
    {/each}
  </tbody>
</table>

// components/cfdt.tsx
import type { FC } from "react";
import { Table, Tbody, Tr, Td, Thead, Th, Text } from "@chakra-ui/react";
import type { Dataset } from "../lib/dataset";

const FDT: FC<{ dataset: Dataset }> = ({ dataset }) => {
  let cf = 0;
  return (
    <>
      <Table>
        <Thead>
          <Tr>
            <Th>
              Score (<em>x</em>)
            </Th>
            <Th>
              Frequency (<em>f</em>)
            </Th>
            <Th>
              Cumulative Frequency (<em>c.f.</em>)
            </Th>
            <Th>
              Cumulative Percentage (<em>c.p.</em>)
            </Th>
          </Tr>
        </Thead>
        <Tbody>
          {dataset.unique.map((x, i) => {
            const f = dataset.count(x);
            cf += f;
            return (
              <Tr key={i}>
                <Td>{x}</Td>
                <Td>{f}</Td>
                <Td>{cf}</Td>
                <Td>{(cf / dataset.data.length) * 100} %</Td>
              </Tr>
            );
          })}
        </Tbody>
      </Table>
      <Text>
        Sum of <em>f</em>:{" "}
        {dataset.unique.map((x) => dataset.count(x)).reduce((a, b) => a + b, 0)}
      </Text>
    </>
  );
};

export default FDT;
